export const themeColors = {
  light: {
    name: "Enterprise",
    bg: "bg-[#FAFAFA]", // Very subtle gray for page bg
    surface: "bg-white",
    text: "text-slate-900",
    textSecondary: "text-slate-500",
    border: "border-slate-200",
    primary: "text-blue-600",
    primaryBg: "bg-blue-600",
    accent: "bg-slate-100",
    cardBg: "bg-white",
    cardHover: "hover:shadow-md",
    shadow: "shadow-sm",
    gradient: "from-blue-600 to-indigo-600", // Professional gradient
    glassBg: "bg-white", // No glass in enterprise usually, just solid clean white
    buttonPrimary: "bg-slate-900 text-white hover:bg-slate-800",
    buttonSecondary: "bg-white text-slate-700 border border-slate-200 hover:bg-slate-50",
  },
  dark: {
    name: "Midnight",
    bg: "bg-slate-950",
    surface: "bg-slate-900",
    text: "text-slate-50",
    textSecondary: "text-slate-400",
    border: "border-slate-800",
    primary: "text-blue-400",
    primaryBg: "bg-blue-500",
    accent: "bg-slate-800",
    cardBg: "bg-slate-900",
    cardHover: "hover:shadow-lg hover:shadow-blue-900/10",
    shadow: "shadow-lg",
    gradient: "from-blue-900 to-indigo-900",
    glassBg: "bg-slate-900/90",
    buttonPrimary: "bg-blue-600 text-white hover:bg-blue-500",
    buttonSecondary: "bg-slate-800 text-slate-200 border border-slate-700 hover:bg-slate-700",
  },
  vintage: {
    name: "Classic",
    bg: "bg-[#FDFBF7]",
    surface: "bg-white",
    text: "text-stone-800",
    textSecondary: "text-stone-500",
    border: "border-stone-200",
    primary: "text-orange-600",
    primaryBg: "bg-orange-600",
    accent: "bg-stone-100",
    cardBg: "bg-[#FAF9F6]",
    cardHover: "hover:shadow-md hover:shadow-orange-900/5",
    shadow: "shadow-sm",
    gradient: "from-orange-400 to-red-400",
    glassBg: "bg-white/90",
    buttonPrimary: "bg-stone-800 text-stone-50 hover:bg-stone-700",
    buttonSecondary: "bg-[#FAF9F6] text-stone-700 border border-stone-200 hover:bg-stone-100",
  }
};
